### ISSUE TITLE
Add xhprof.io to Packagist

### ISSUE THREAD

**Issue by maxromanovsky** [gajus/xhprof.io#54]
Please add  xhprof.io to [Packagist](https://packagist.org). It would allow to include it as a library

**Comment by jcrben** [comment]
@gajus the latest commit https://github.com/gajus/xhprof.io/commit/6ec59d975a57d09808a24d7cee84e1d40e0efa65 said "If you'd like to take over active maintenance of this project, please contact the project author"

Why not bring @staabm on as a collaborator?
